scriptencoding utf-8
set encoding=utf-8

colorscheme evening
syntax on
set number
set tabstop=4
set shiftwidth=4
set autoindent
set cursorline

" highlight trailing spaces and tabs
set list!
set listchars=tab:»·,trail:·

" set viminfo
set viminfo='10,"\100,:20,%,n~/.viminfo

" return to last line, when opening a file again
function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction

augroup resCur
  autocmd!
  autocmd BufWinEnter * call ResCur()
augroup END

filetype indent plugin on

" never expand tabs in Makefiles - bugs them out
autocmd FileType make setlocal noexpandtab
" expand tabs in perl and config files
autocmd FileType perl setlocal expandtab
autocmd FileType conf setlocal expandtab
autocmd FileType apache setlocal expandtab
" python settings
autocmd FileType python setlocal tabstop=8 expandtab shiftwidth=4 softtabstop=4 

" perl smartsearch: if lowercase, ignore case
set ignorecase
set smartcase
set incsearch

" bind F4 to hlsearch
set hlsearch
noremap <F4> :set hlsearch! hlsearch?<CR>

" ugly block comment macro
let @a='I#OBOA'

" map <F5> to comment and <F6> to pseudo uncomment
noremap <F5> @a
noremap <F6> x

" better file completition while opening files from vim
set wildmode=list:longest

source ~/.vimrc.more
