scriptencoding utf-8
set encoding=utf-8

syntax on
set tabstop=4
set shiftwidth=4
set autoindent

" Colorscheme
colorscheme elflord
set bg=dark
set t_Co=256

" highlight trailing spaces and tabs
set list!
set listchars=tab:»·,trail:·

" set viminfo
set viminfo='10,"\100,:20,%,n~/.viminfo

" return to last line, when opening a file again
function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction

augroup resCur
  autocmd!
  autocmd BufWinEnter * call ResCur()
augroup END

filetype indent plugin on

" never expand tabs in Makefiles - bugs them out
autocmd FileType make setlocal noexpandtab
" Perl: expand tabs, use fold markers
autocmd FileType perl setlocal expandtab
autocmd FileType perl setlocal foldmethod=marker foldlevel=1
" Clean tabs for .conf and apache files
autocmd FileType conf setlocal expandtab
autocmd FileType apache setlocal expandtab
" python settings
autocmd FileType python setlocal tabstop=8 expandtab shiftwidth=4 softtabstop=4
" javascript settings
autocmd FileType javascript setlocal tabstop=2 expandtab shiftwidth=2 softtabstop=2
" Puppet files
autocmd BufRead,BufNewFile *.pp setlocal noexpandtab

" perl smartsearch: if lowercase, ignore case
set ignorecase
set smartcase
set incsearch

" bind F4 to hlsearch
set hlsearch
noremap <F4> :set hlsearch! hlsearch?<CR>

" ugly block comment macro
let @a='I#OBOA'

" map <F5> to comment and <F6> to pseudo uncomment
noremap <F5> @a
noremap <F6> x

" better file completition while opening files from vim
set wildmode=list:longest

""" Plugins
"" pathogen
execute pathogen#infect()

"" vim-airline
" hide mode indicator from vanilla vim
set noshowmode
" autoshow
set laststatus=2
" fugitive integration
let g:airline#extensions#branch#enabled = 1
" powerline font
set guifont=DejaVu\ Sans\ Mono\ for\ Powerline\ 8
let g:airline_powerline_fonts = 1

source ~/.vimrc.more
