colorscheme evening
syntax on
set number
set tabstop=4
set shiftwidth=4
set autoindent
set cursorline

" highlight trailing spaces and tabs
set list!
set listchars=tab:»·,trail:·


set viminfo='10,"\100,:20,%,n~/.viminfo

" return to last line
function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction

augroup resCur
  autocmd!
  autocmd BufWinEnter * call ResCur()
augroup END

" never expand tabs in Makefiles - bugs them out
autocmd FileType make setlocal noexpandtab
" expand tabs in perl
autocmd FileType perl setlocal expandtab

" perl smartsearch: if lowercase, ignore case
set ignorecase
set smartcase
set incsearch

" bind F4 to hlsearch
set hlsearch
noremap <F4> :set hlsearch! hlsearch?<CR>
