# The following lines were added by compinstall
zstyle :compinstall filename '/home/maik/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install

autoload -U promptinit
promptinit
prompt redhat

# fancy completion

zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ''


# aliases

alias ls="ls --color=auto"
alias ll="ls -l"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias sudude="sudo"
# meme alias
alias wow="git status"
alias such="git"
alias many="git"
alias very="git"
alias much="git"

# add local bin to path
export PATH=~/bin:$PATH

# keybindings

bindkey '^R' history-incremental-search-backward

