# The following lines were added by compinstall
zstyle :compinstall filename '/home/glatki/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=$HISTSIZE
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install

## Prompt configuration
autoload -U promptinit && promptinit
autoload -U colors && colors
local pr_reset="%{$reset_color%}"
PROMPT="%~%{$reset_color%}%{$fg[red]%} %?↵%{$fg_bold[blue]%}#%{$reset_color%}%}"
PROMPT="%{$bg[white]%}%(!.%{$fg[red]%}.%{$fg[blue]%})"
PROMPT+="%U%n@%m%u"
PROMPT+="%{$reset_color $fg_bold[blue]%}"
PROMPT+="%~${pr_reset}%{$fg[red]%}"
PROMPT+="%?↵%{$fg_bold[blue]%}"
PROMPT+="#$pr_reset  "
# show time on right side.
RPROMPT="[%T]"

# fancy completion
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ''

# aliases
alias tmux="tmux -2"
alias ls="ls --color=auto"
alias ll="ls -l"
alias ggrep="git grep"
# FIXME refactor into a function.
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
# I want ifconfig everywhere
alias ifconfig="PATH=/sbin ifconfig"
# noglobs
alias find='noglob find'
alias systemctl='noglob systemctl'
## stupic alias section
alias sudude="sudo"
alias please='sudo $(history -n -1)'
# meme alias
alias wow="git status"
alias such="git"
alias many="git"
alias very="git"
alias much="git"
# VUM!
alias vum="vim"

# add local bin to path
export PATH=~/bin:$PATH
# export vim as editor
export EDITOR=vim

# keybindings
case $TERM in
  linux|screen)
    bindkey "^[[2~" yank
    bindkey "^[[3~" delete-char
    bindkey "^[[1~" beginning-of-line
    bindkey "^[[4~" end-of-line
  ;;
  *xterm*|rxvt*|(dt|k|E|a)term)
    bindkey "^[[2~" yank
    bindkey "^[[3~" delete-char
    bindkey "^[[7~" beginning-of-line
    bindkey "^[[8~" end-of-line
  ;;
esac

bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
bindkey '^[OF' end-of-line
bindkey '^[OH' beginning-of-line
bindkey '^R' history-incremental-search-backward

# skipping words via CTRL-RightArrow/LeftArrow
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word

# ignore debian global rc file
unsetopt global_rcs

if [ -f ~/.zshrc.more ]; then
	source ~/.zshrc.more
fi
