# The following lines were added by compinstall
zstyle :compinstall filename '/home/maik/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install

# prompt config
autoload -U promptinit && promptinit
autoload -U colors && colors

# prompt config
PROMPT="%(!.%{$bg[white]$fg[red]%}%U%n@%m%u%{$reset_color $fg_bold[blue]%} %~# %{$reset_color%}.%{$bg[white]$fg[blue]%}%U%n@%m%u%{$reset_color $fg_bold[blue]%} %~# %{$reset_color%})"
# show time on right side
RPROMPT="[%T]"

# fancy completion

zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ''


# aliases

alias ls="ls --color=auto"
alias ll="ls -l"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias sudude="sudo"
alias please='sudo $(history -n -1)'
alias find='noglob find'
# meme alias
alias wow="git status"
alias such="git"
alias many="git"
alias very="git"
alias much="git"
# VUM!
alias vum="vim"
# I want ifconfig everywhere
alias ifconfig="PATH=/sbin ifconfig"


# add local bin to path
export PATH=~/bin:$PATH
# export vim as editor
export EDITOR=vim

# keybindings
case $TERM in
  linux|screen)
    bindkey "^[[2~" yank
    bindkey "^[[3~" delete-char
    bindkey "^[[1~" beginning-of-line
    bindkey "^[[4~" end-of-line
  ;;
  *xterm*|rxvt*|(dt|k|E|a)term)
    bindkey "^[[2~" yank
    bindkey "^[[3~" delete-char
    bindkey "^[[7~" beginning-of-line
    bindkey "^[[8~" end-of-line
  ;;
esac

bindkey '^R' history-incremental-search-backward
bindkey '^[OF' end-of-line
bindkey '^[OH' beginning-of-line

if [ -f ~/.zshrc.more ]; then
	source ~/.zshrc.more
fi
